In [1]:
import numpy as np
print('NumPy Version:', np.__version__)

NumPy Version: 2.0.2


In [3]:
#Problem 1: Clip Values to Range
arr = np.array([5, 12, 25, 7, 30, 18])
clipped = np.clip(arr, 10, 20)
print(clipped)

[10 12 20 10 20 18]


In [4]:
#Problem 2: Find Indices of Even Numbers
arr = np.array([11, 24, 37, 42, 56, 63])
indices = np.where(arr % 2 == 0)
print(indices[0])

[1 3 4]


In [5]:
#Problem 3: Compute Row-wise Maximum
matrix = np.array([[5, 9, 1],
                   [7, 3, 8],
                   [4, 6, 2]])
print(np.max(matrix, axis=1))

[9 8 6]


In [6]:
#Problem 4: Flatten a Matrix
matrix = np.array([[1,2,3],
                   [4,5,6]])
print(matrix.flatten())

[1 2 3 4 5 6]


In [7]:
#Problem 5: Find Common Elements Between Arrays
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
common = np.intersect1d(a, b)
print(common)

[4 5]


In [8]:
#Problem 7: Find Top 3 Largest Elements
arr = np.array([15, 3, 27, 9, 40, 22])
top3 = np.sort(arr)[-3:]
print(top3)

[22 27 40]


In [9]:
#Problem 8: Swap First and Last Row
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

matrix[[0, -1]] = matrix[[-1, 0]]
print(matrix)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [10]:
#Problem 9: Create Identity Matrix and Verify
I = np.eye(4)
print(I)

print("Check I @ I equals I:")
print(np.allclose(I @ I, I))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Check I @ I equals I:
True


In [11]:
#Problem 10: Rolling Window Sum
arr = np.array([1,2,3,4,5,6])
window_sum = np.convolve(arr, np.ones(3, dtype=int), 'valid')
print(window_sum)

[ 6  9 12 15]


In [12]:
#Mini Data Science Practice
np.random.seed(42)
sales = np.random.randint(100, 1000, 500)

print('Average Sales:', np.mean(sales))
print('High Sales (>800):', np.sum(sales > 800))

categories = np.where(sales >= 800, 'High',
              np.where(sales >= 500, 'Medium', 'Low'))

print('Sample Categories:', categories[:10])

Average Sales: 558.358
High Sales (>800): 115
Sample Categories: ['Low' 'Medium' 'High' 'Low' 'Low' 'Low' 'High' 'Low' 'Medium' 'Low']
